#!/usr/bin/env python3
"""
Build the agentgateway config.yaml by inlining the Reflexive-Core framework XML.

Outputs two listeners on the same gateway binary:

  :1235 = RC ON   — promptEnrichment prepends framework as system message,
                    response webhook gates on framework decision
  :1237 = RC OFF  — pure passthrough to LM Studio (no system injection,
                    no webhook), kept on the gateway so RC ON / OFF cells
                    share identical network topology

Both listeners route to LM Studio at 127.0.0.1:1234 via the openai
provider with hostOverride. Run this script whenever the framework
file changes; the generated config.yaml is committed only if you want it,
otherwise treat as a build artifact.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path
from textwrap import indent

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
FRAMEWORK_PATH = REPO_ROOT / "framework" / "reflexive-core-prod.xml"
OUT_PATH = HERE / "config.yaml"

LM_STUDIO_HOST = "127.0.0.1:1234"
PORT_RC_ON = 1235
PORT_RC_OFF = 1237
WEBHOOK_TARGET = "127.0.0.1:1236"


def main() -> int:
    xml = FRAMEWORK_PATH.read_text(encoding="utf-8")
    xml_sha = hashlib.sha256(xml.encode("utf-8")).hexdigest()
    # The `content: |` key sits at column 23 (22 spaces); YAML block-scalar
    # content must be indented MORE than the key. Use 24 spaces so the XML
    # sits one level deeper, comfortably inside the block.
    xml_indented = indent(xml, " " * 24)

    yaml = f"""# yaml-language-server: $schema=https://agentgateway.dev/schema/config
#
# Auto-generated by gateway/build_config.py — do not edit by hand.
# Framework SHA256: {xml_sha}
# Source: framework/reflexive-core-prod.xml
#
# RC ON path uses webhook on BOTH request and response sides:
#   request webhook  — wraps incoming content as <rc:user:NONCE>/<rc:tool:NONCE>
#                      and injects framework XML as system message
#   response webhook — parses framework JSON, returns canonical refusal or
#                      masked output per gating decision
# prompts.prepend is intentionally NOT used — the framework is injected by
# the request webhook so the wrap and the framework arrive atomically.

binds:
  # ─────────── RC ON: request-wrap + response-gate via webhooks ───────────
  - port: {PORT_RC_ON}
    listeners:
      - name: rc-on
        routes:
          - backends:
              - ai:
                  name: lmstudio-rc-on
                  hostOverride: "{LM_STUDIO_HOST}"
                  provider:
                    openAI: {{}}
            policies:
              ai:
                promptGuard:
                  request:
                    - webhook:
                        target:
                          host: "{WEBHOOK_TARGET}"
                  response:
                    - webhook:
                        target:
                          host: "{WEBHOOK_TARGET}"

  # ─────────── RC OFF: pure passthrough to LM Studio ───────────
  - port: {PORT_RC_OFF}
    listeners:
      - name: rc-off
        routes:
          - backends:
              - ai:
                  name: lmstudio-rc-off
                  hostOverride: "{LM_STUDIO_HOST}"
                  provider:
                    openAI: {{}}
"""

    OUT_PATH.write_text(yaml, encoding="utf-8")
    print(f"[build_config] wrote {OUT_PATH}")
    print(f"[build_config] framework SHA256: {xml_sha}")
    print(f"[build_config] RC ON  → http://127.0.0.1:{PORT_RC_ON}/v1/chat/completions")
    print(f"[build_config] RC OFF → http://127.0.0.1:{PORT_RC_OFF}/v1/chat/completions")
    print(f"[build_config] webhook target: {WEBHOOK_TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
